// <auto-generated />
namespace IdentitySample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ativo_em_acervo_e_livros : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ativo_em_acervo_e_livros));
        
        string IMigrationMetadata.Id
        {
            get { return "202111291351501_Ativo_em_acervo_e_livros"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
